/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProviderSlugRouteImport } from './routes/provider.$slug'
import { Route as DashboardStaffRouteImport } from './routes/dashboard.staff'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BookConfirmedBookingIdRouteImport } from './routes/book.confirmed.$bookingId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ProviderSlugRoute = ProviderSlugRouteImport.update({
  id: '/provider/$slug',
  path: '/provider/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmedBookingIdRoute = BookConfirmedBookingIdRouteImport.update({
  id: '/book/confirmed/$bookingId',
  path: '/book/confirmed/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/search': typeof SearchRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/book/confirmed/$bookingId': typeof BookConfirmedBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/search': typeof SearchRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/book/confirmed/$bookingId': typeof BookConfirmedBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/search': typeof SearchRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/book/confirmed/$bookingId': typeof BookConfirmedBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/search'
    | '/book/$slug'
    | '/dashboard/calendar'
    | '/dashboard/customers'
    | '/dashboard/services'
    | '/dashboard/staff'
    | '/provider/$slug'
    | '/dashboard/'
    | '/book/confirmed/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my-bookings'
    | '/search'
    | '/book/$slug'
    | '/dashboard/calendar'
    | '/dashboard/customers'
    | '/dashboard/services'
    | '/dashboard/staff'
    | '/provider/$slug'
    | '/dashboard'
    | '/book/confirmed/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/search'
    | '/book/$slug'
    | '/dashboard/calendar'
    | '/dashboard/customers'
    | '/dashboard/services'
    | '/dashboard/staff'
    | '/provider/$slug'
    | '/dashboard/'
    | '/book/confirmed/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  SearchRoute: typeof SearchRoute
  BookSlugRoute: typeof BookSlugRoute
  ProviderSlugRoute: typeof ProviderSlugRoute
  BookConfirmedBookingIdRoute: typeof BookConfirmedBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/provider/$slug': {
      id: '/provider/$slug'
      path: '/provider/$slug'
      fullPath: '/provider/$slug'
      preLoaderRoute: typeof ProviderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmed/$bookingId': {
      id: '/book/confirmed/$bookingId'
      path: '/book/confirmed/$bookingId'
      fullPath: '/book/confirmed/$bookingId'
      preLoaderRoute: typeof BookConfirmedBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  SearchRoute: SearchRoute,
  BookSlugRoute: BookSlugRoute,
  ProviderSlugRoute: ProviderSlugRoute,
  BookConfirmedBookingIdRoute: BookConfirmedBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
