/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderSlugRouteImport } from './routes/provider.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BookConfirmedBookingIdRouteImport } from './routes/book.confirmed.$bookingId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSlugRoute = ProviderSlugRouteImport.update({
  id: '/provider/$slug',
  path: '/provider/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmedBookingIdRoute = BookConfirmedBookingIdRouteImport.update({
  id: '/book/confirmed/$bookingId',
  path: '/book/confirmed/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/search': typeof SearchRoute
  '/book/$slug': typeof BookSlugRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/book/confirmed/$bookingId': typeof BookConfirmedBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/search': typeof SearchRoute
  '/book/$slug': typeof BookSlugRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/book/confirmed/$bookingId': typeof BookConfirmedBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/search': typeof SearchRoute
  '/book/$slug': typeof BookSlugRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/book/confirmed/$bookingId': typeof BookConfirmedBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/search'
    | '/book/$slug'
    | '/provider/$slug'
    | '/book/confirmed/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/search'
    | '/book/$slug'
    | '/provider/$slug'
    | '/book/confirmed/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/search'
    | '/book/$slug'
    | '/provider/$slug'
    | '/book/confirmed/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  SearchRoute: typeof SearchRoute
  BookSlugRoute: typeof BookSlugRoute
  ProviderSlugRoute: typeof ProviderSlugRoute
  BookConfirmedBookingIdRoute: typeof BookConfirmedBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$slug': {
      id: '/provider/$slug'
      path: '/provider/$slug'
      fullPath: '/provider/$slug'
      preLoaderRoute: typeof ProviderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmed/$bookingId': {
      id: '/book/confirmed/$bookingId'
      path: '/book/confirmed/$bookingId'
      fullPath: '/book/confirmed/$bookingId'
      preLoaderRoute: typeof BookConfirmedBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  SearchRoute: SearchRoute,
  BookSlugRoute: BookSlugRoute,
  ProviderSlugRoute: ProviderSlugRoute,
  BookConfirmedBookingIdRoute: BookConfirmedBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
