/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProviderSlugRouteImport } from './routes/provider.$slug'
import { Route as OrganizationsNewRouteImport } from './routes/organizations.new'
import { Route as DashboardStaffRouteImport } from './routes/dashboard.staff'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardResourcesRouteImport } from './routes/dashboard.resources'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard.marketing'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'
import { Route as DashboardEmailSettingsRouteImport } from './routes/dashboard.email-settings'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardAuditLogRouteImport } from './routes/dashboard.audit-log'
import { Route as DashboardAiAssistantRouteImport } from './routes/dashboard.ai-assistant'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BookConfirmedBookingIdRouteImport } from './routes/book.confirmed.$bookingId'
import { Route as AdminViewUserIdRouteImport } from './routes/admin.view.$userId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ProviderSlugRoute = ProviderSlugRouteImport.update({
  id: '/provider/$slug',
  path: '/provider/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailSettingsRoute = DashboardEmailSettingsRouteImport.update({
  id: '/email-settings',
  path: '/email-settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogRoute = DashboardAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiAssistantRoute = DashboardAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => DashboardRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmedBookingIdRoute = BookConfirmedBookingIdRouteImport.update({
  id: '/book/confirmed/$bookingId',
  path: '/book/confirmed/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViewUserIdRoute = AdminViewUserIdRouteImport.update({
  id: '/view/$userId',
  path: '/view/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/email-settings': typeof DashboardEmailSettingsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/view/$userId': typeof AdminViewUserIdRoute
  '/book/confirmed/$bookingId': typeof BookConfirmedBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/email-settings': typeof DashboardEmailSettingsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/view/$userId': typeof AdminViewUserIdRoute
  '/book/confirmed/$bookingId': typeof BookConfirmedBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/email-settings': typeof DashboardEmailSettingsRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/provider/$slug': typeof ProviderSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/view/$userId': typeof AdminViewUserIdRoute
  '/book/confirmed/$bookingId': typeof BookConfirmedBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/search'
    | '/book/$slug'
    | '/dashboard/ai-assistant'
    | '/dashboard/audit-log'
    | '/dashboard/calendar'
    | '/dashboard/customers'
    | '/dashboard/email-settings'
    | '/dashboard/inventory'
    | '/dashboard/marketing'
    | '/dashboard/reports'
    | '/dashboard/resources'
    | '/dashboard/reviews'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/organizations/new'
    | '/provider/$slug'
    | '/dashboard/'
    | '/admin/view/$userId'
    | '/book/confirmed/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/search'
    | '/book/$slug'
    | '/dashboard/ai-assistant'
    | '/dashboard/audit-log'
    | '/dashboard/calendar'
    | '/dashboard/customers'
    | '/dashboard/email-settings'
    | '/dashboard/inventory'
    | '/dashboard/marketing'
    | '/dashboard/reports'
    | '/dashboard/resources'
    | '/dashboard/reviews'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/organizations/new'
    | '/provider/$slug'
    | '/dashboard'
    | '/admin/view/$userId'
    | '/book/confirmed/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/my-bookings'
    | '/profile'
    | '/search'
    | '/book/$slug'
    | '/dashboard/ai-assistant'
    | '/dashboard/audit-log'
    | '/dashboard/calendar'
    | '/dashboard/customers'
    | '/dashboard/email-settings'
    | '/dashboard/inventory'
    | '/dashboard/marketing'
    | '/dashboard/reports'
    | '/dashboard/resources'
    | '/dashboard/reviews'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/organizations/new'
    | '/provider/$slug'
    | '/dashboard/'
    | '/admin/view/$userId'
    | '/book/confirmed/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  BookSlugRoute: typeof BookSlugRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  ProviderSlugRoute: typeof ProviderSlugRoute
  BookConfirmedBookingIdRoute: typeof BookConfirmedBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/provider/$slug': {
      id: '/provider/$slug'
      path: '/provider/$slug'
      fullPath: '/provider/$slug'
      preLoaderRoute: typeof ProviderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resources': {
      id: '/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/email-settings': {
      id: '/dashboard/email-settings'
      path: '/email-settings'
      fullPath: '/dashboard/email-settings'
      preLoaderRoute: typeof DashboardEmailSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit-log': {
      id: '/dashboard/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/audit-log'
      preLoaderRoute: typeof DashboardAuditLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-assistant': {
      id: '/dashboard/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/dashboard/ai-assistant'
      preLoaderRoute: typeof DashboardAiAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmed/$bookingId': {
      id: '/book/confirmed/$bookingId'
      path: '/book/confirmed/$bookingId'
      fullPath: '/book/confirmed/$bookingId'
      preLoaderRoute: typeof BookConfirmedBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/view/$userId': {
      id: '/admin/view/$userId'
      path: '/view/$userId'
      fullPath: '/admin/view/$userId'
      preLoaderRoute: typeof AdminViewUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminViewUserIdRoute: typeof AdminViewUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminViewUserIdRoute: AdminViewUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAiAssistantRoute: typeof DashboardAiAssistantRoute
  DashboardAuditLogRoute: typeof DashboardAuditLogRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardEmailSettingsRoute: typeof DashboardEmailSettingsRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardMarketingRoute: typeof DashboardMarketingRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardResourcesRoute: typeof DashboardResourcesRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiAssistantRoute: DashboardAiAssistantRoute,
  DashboardAuditLogRoute: DashboardAuditLogRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardEmailSettingsRoute: DashboardEmailSettingsRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardMarketingRoute: DashboardMarketingRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardResourcesRoute: DashboardResourcesRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  BookSlugRoute: BookSlugRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  ProviderSlugRoute: ProviderSlugRoute,
  BookConfirmedBookingIdRoute: BookConfirmedBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
